npys_dir:
  features: "features"  # Directory with .npy feature files inside class subfolders

data:
  aud_train_dir: "dataset/audio/train"
  aud_val_dir: "dataset/audio/val"
  aud_test_dir: "dataset/audio/test"

ckpt:
  root: "checkpoints"
  audio_model: "checkpoints/audio_emotion_cnn1d.pth"

results:
  root: "results"

classes:
  - Angry
  - Disgust
  - Fear
  - Happy
  - Neutral
  - Sad

training:
  batch_size: 32
  num_workers: 4
  input_features: 39
  epochs: 30
  lr: 0.001

preprocessing:
  
  sample_rate: 16000
  n_mfcc: 13
  win_length: 0.025
  hop_length: 0.010

demo:
  video_clip: "C:/Users/Dator/Pictures/Camera Roll/1.mp4"
  csv_out: "results/output.csv"
  frames: 10
  audio_window: 1.0
